CREATE USER admin WITH PASSWORD 'mypassword1234';
CREATE DATABASE movies_database;
GRANT ALL PRIVILEGES ON DATABASE movies_database TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
